services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tienda
      MYSQL_USER: Francisco
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"